version: "3.8"

services:
  mysqldb:
    container_name: mysqldbv1
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - custom
  app:
    container_name: app
    depends_on:
      - mysqldb
    image: iomega/infineon-fullstack-app
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - DOCKER_MYSQL_SPRINGBOOT_DEMO_MYSQL_HOST=mysqldbv1
    stdin_open: true
    tty: true
    networks:
      - custom

  app-ui:
    depends_on:
      - app
    image: iomega/infineon-fullstack-app-ui
    env_file: ./.env
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - custom 
      
volumes:
  db:


networks:
  custom:
